using UnityEngine;
using UnityEditor;
using UnityEngine.UIElements;
using System.IO;
using System.Diagnostics;
using System;
using System.Threading;
using System.Linq;
using System.IO.Enumeration;
using System.Collections;

public class RunTrellis : EditorWindow
{
    private static string fileName;

    private static string imageFilePath;
    private static string imagePrompt;


    // Full path to where meshes generated by TRELLIS are saved
    private static readonly string trellisSavelocation = Path.GetFullPath("../TRELLIS.2/GeneratedMeshesUnity");
    private static readonly string trellisPath = Path.GetFullPath("../TRELLIS.2");
    private static readonly string trellisProcessingLock = "trellisProcessing.lock";
    private static readonly string targetPathModel = "Assets/Resources/privateResources/Trellis/models";
    private static readonly string targetPathPrefab = "Assets/Resources/privateResources/Trellis/prefabs";

    // Full path to where images generated by Wan2GP are saved
    private static readonly string wan2gpSaveLocation = Path.GetFullPath("../Wan2GP/GeneratedImagesUnity");
    private static readonly string wan2gpPath = Path.GetFullPath("../Wan2GP");
    private static readonly string wan2gpProcessingLock = "wan2gpProcessing.lock";
    
    // Full path to where test results are saved
    private static readonly string testSaveLocation = Path.GetFullPath("../TRELLIS.2-tests");


    [MenuItem("Tools/Run Python Script")]
    private static void RunPythonScript()
    {
        // Ask optional prompt from user and run scripts
        RunTrellis window = ScriptableObject.CreateInstance<RunTrellis>();
        window.position = new Rect(Screen.width / 2, Screen.height / 2, 250, 150);
        window.ShowUtility();
    }

    /// <summary>
    /// Run TRELLIS script to generate 3D model and import it as prefab into Unity
    /// </summary>
    /// <param name="useImageFilePath">Whether to use an existing image as input for TRELLIS</param>
    private static void RunTrellisScript(bool useImageFilePath = false)
    {
        string scriptCommand = useImageFilePath ? 
            $"-i -l -c \"'{trellisPath}/app_unity.sh' '{fileName}' '{trellisSavelocation}' '{testSaveLocation}' '{imageFilePath}'\""
            : $"-i -l -c \"'{trellisPath}/app_unity.sh' '{fileName}' '{trellisSavelocation}' '{testSaveLocation}'\"";

        ProcessStartInfo startTrellis = new()
        {
            FileName = "/bin/bash",
            Arguments = scriptCommand,
            WorkingDirectory = $"{trellisPath}/",
            UseShellExecute = false,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            CreateNoWindow = false
        };
        Process process = Process.Start(startTrellis);

        // need to use blocking call cause AssetDatabase.Refresh(); can only run on main thread
        // Cannot use FileSystemWatcher on Linux/MacOS reliably, so using polling instead
        string lockPath = $"{trellisSavelocation}/{trellisProcessingLock}";
        while (!File.Exists(lockPath)) 
        {
            Thread.Sleep(50);
        }
        while (File.Exists(lockPath)) 
        {
            Thread.Sleep(50);
        }

        UnityEngine.Debug.Log($"stdout: {process.StandardOutput.ReadToEnd()}\nstderr: {process.StandardError.ReadToEnd()}");

        string sourceFilePath = $"{trellisSavelocation}/{fileName}.glb";
        if (!File.Exists(sourceFilePath))
        {
            UnityEngine.Debug.LogError("TRELLIS script did not generate a .glb file.");
            return;
        }

        string targetFilePath = $"{targetPathModel}/{fileName}.glb";
        string directory = Path.GetDirectoryName(targetFilePath);
        if (!Directory.Exists(directory))
        {
            Directory.CreateDirectory(directory);
        }

        File.Copy(sourceFilePath, targetFilePath, true);
        AssetDatabase.Refresh();

        GameObject importedAsset = AssetDatabase.LoadAssetAtPath<GameObject>(targetFilePath);
        GameObject instance = (GameObject)PrefabUtility.InstantiatePrefab(importedAsset);
        MeshCollider collider = instance.GetComponentInChildren<MeshFilter>().gameObject.AddComponent<MeshCollider>();
        collider.convex = true;
        instance.AddComponent<Rigidbody>();

        string prefabPath = $"{targetPathPrefab}/{fileName}.prefab";
        directory = Path.GetDirectoryName(prefabPath);
        if (!Directory.Exists(directory))
        {
            Directory.CreateDirectory(directory);
        }
        PrefabUtility.SaveAsPrefabAsset(instance, prefabPath);
        GameObject.DestroyImmediate(instance);
        UnityEngine.Debug.Log("Finished prefab creation");
    }

    /// <summary>
    /// Run Wan2GP script to generate image from prompt
    /// </summary>
    private static void RunWan2GPScript()
    {
        string scriptCommand = $"-i -l -c \"'{wan2gpPath}/wgp_unity.sh' '{imagePrompt}' '{wan2gpSaveLocation}' '{testSaveLocation}/{fileName}'\"";

        ProcessStartInfo startWan2GP = new()
        {
            FileName = "/bin/bash",
            Arguments = scriptCommand,
            WorkingDirectory = $"{wan2gpPath}/",
            UseShellExecute = false,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            CreateNoWindow = false
        };
        Process process = Process.Start(startWan2GP);

        // need to use blocking call cause AssetDatabase.Refresh(); can only run on main thread
        // Cannot use FileSystemWatcher on Linux/MacOS reliably, so using polling instead
        string lockPath = $"{wan2gpSaveLocation}/{wan2gpProcessingLock}";
        while (!File.Exists(lockPath))
        {
            Thread.Sleep(50);
        }
        while (File.Exists(lockPath)) 
        {
            Thread.Sleep(50);
        }

        // Get jpg file path from test folder
        string[] jpgFiles = Directory.GetFiles($"{testSaveLocation}/{fileName}", "*.jpg");
        if (jpgFiles.Length == 0)
        {
            UnityEngine.Debug.LogError("Wan2GP script did not generate a .jpg file.");
            return;
        }
        imageFilePath = jpgFiles[0];

        UnityEngine.Debug.Log($"stdout: {process.StandardOutput.ReadToEnd()}\nstderr: {process.StandardError.ReadToEnd()}");
    }
    
    /// <summary>
    /// Create GUI for optional prompt input before running TRELLIS
    /// </summary>
    void CreateGUI()
    {
        var label = new Label("TRELLIS generation");
        rootVisualElement.Add(label);

        var textbox = new TextField("(Optional) Enter Text Prompt:");
        var slider = new SliderInt("Number of Iterations:", 1, 20);
        slider.SetEnabled(false);
        var valueText = new TextField("Number of models:");
        valueText.SetEnabled(false);
        textbox.RegisterValueChangedCallback(evt => {
            if (string.IsNullOrEmpty(evt.newValue)) {
                // Deactivate slider if no prompt provided
                slider.SetEnabled(false);
                valueText.SetEnabled(false);
                valueText.value = "1";
            }
            else {
                slider.SetEnabled(true);
                valueText.SetEnabled(true);
                valueText.value = $"{slider.value}";
            }
        });
        slider.RegisterValueChangedCallback(evt => {
            valueText.value = $"{evt.newValue}";
        });
        valueText.RegisterValueChangedCallback(evt => {
            if (int.TryParse(evt.newValue, out int newValue)) {
                if (newValue < slider.lowValue) {
                    newValue = (int)slider.lowValue;
                }
                if (newValue > slider.highValue) {
                    newValue = (int)slider.highValue;
                }
                slider.value = newValue;
            }
            else {
                valueText.value = $"{slider.value}";
            }
        });
        rootVisualElement.Add(textbox);
        rootVisualElement.Add(slider);
        rootVisualElement.Add(valueText);

        var button = new Button
        {
            text = "Generate"
        };
        button.clicked += () =>
        {
            imagePrompt = textbox.value;
            string shortFileName = $"{Directory.GetFileSystemEntries(trellisSavelocation).Length}";
            int iterationCount = slider.value;
            fileName = shortFileName;
            
            this.Close();

            if (string.IsNullOrEmpty(imagePrompt))
            {
                // No prompt provided -> just run trellis script
                UnityEngine.Debug.Log("Running TRELLIS without prompt...");
                RunTrellisScript();
            }
            else
            {
                UnityEngine.Debug.Log($"Running Wan2GP and TRELLIS with prompt: {imagePrompt}");

                if (iterationCount == 1) {
                    // Generate image using wan2gp
                    RunWan2GPScript();

                    // Do like previous script but use generated image path as argument for app_unity.sh
                    RunTrellisScript(true /* use generated image as input */);
                }
                else {
                    // Generate multiple models by running wan2gp and trellis in a loop, appending iteration number to file name
                    for (int i = 0; i < iterationCount; i++) {
                        fileName = $"{shortFileName}/{i}";

                        // Generate image using wan2gp
                        RunWan2GPScript();

                        // Do like previous script but use generated image path as argument for app_unity.sh
                        RunTrellisScript(true /* use generated image as input */);
                    }
                }                
            }            
        };
        rootVisualElement.Add(button);

        var cancelButton = new Button
        {
            text = "Cancel"
        };
        cancelButton.clicked += () =>
        {
            this.Close();
            UnityEngine.Debug.Log("TRELLIS generation cancelled by user.");
        };
        rootVisualElement.Add(cancelButton);
    }
}
